### ISSUE TITLE
Create vaporetto instance take long time

### ISSUE THREAD

**Issue by rabbit19981023** [daac-tools/python-vaporetto#6]
### Environment
- CPU: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz   2.71 GHz
- Memory: 20GB
- Platform: Docker inside WSL 2
- Docker version: 23.0.1
- Python version: 3.11.2
- Vaporetto version: 0.2.0
- Model: bccwj-suw+unidic+tag.model.zst 0.5.0

# Description
I followed the example, but always take a lot of time. I'm not sure if this is normal.

My codes:
```python
# Import vaporetto module
import vaporetto
import time

start = time.time()

# Load the model file
with open('./bccwj.model.zst', 'rb') as fp:
    model = fp.read()

# Create an instance of the Vaporetto
tokenizer = vaporetto.Vaporetto(model, predict_tags = True)

end = time.time()

print('The time it takes to create an instance: ', end - start)
# The time it takes to create an instance:  7.959897994995117
```

**Comment by vbkaisetsu** [comment]
Thank you for the report.

This is normal behavior.
Vaporetto has several elements that take a long time to initialize. One of the main reasons is that it builds a pattern match automaton from dictionary words and n-grams contained in the model file.
It is possible to include the pre-built automaton in the model file like KyTea, but the model file tends to be huge.
There is also concern that the specification to load pre-built automaton is a security hole since there is no mechanism to protect against untrusted models.

For these reasons, Vaporetto builds an automaton at initialization.
